### ISSUE TITLE
Error while executing Spark Streaming ..."C:\bigdata\spark-2.4.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\worker.py", line 25, in ModuleNotFoundError: No module named 'resource'

### ISSUE THREAD

**Issue by ClonetApp** [ClonetApp/Python#2]

**Comment by ClonetApp** [comment]
Error Message:

2019-10-17   09:49:05 INFO  JobScheduler:54 - Added   jobs for time 1571323745000 ms
--
Traceback (most recent call last):
File "C:\ana\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\ana\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File   "C:\bigdata\spark-2.4.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\worker.py",   line 25, in <module>
ModuleNotFoundError: No module named   'resource'
2019-10-17 09:49:06 INFO  JobScheduler:54 - Added jobs for time   1571323746000 ms
2019-10-17 09:49:07 INFO  JobScheduler:54 - Added jobs for time   1571323747000 ms
2019-10-17 09:49:08 INFO  JobScheduler:54 - Added jobs for time   1571323748000 ms
2019-10-17 09:49:09 INFO  JobScheduler:54 - Added jobs for time   1571323749000 ms
2019-10-17 09:49:10 INFO  JobScheduler:54 - Added jobs for time   1571323750000 ms
2019-10-17 09:49:11 INFO  JobScheduler:54 - Added jobs for time   1571323751000 ms
2019-10-17 09:49:12 INFO  JobScheduler:54 - Added jobs for time   1571323752000 ms
2019-10-17 09:49:13 INFO  JobScheduler:54 - Added jobs for time   1571323753000 ms
2019-10-17 09:49:14 INFO  JobScheduler:54 - Added jobs for time   1571323754000 ms
2019-10-17 09:49:14 ERROR Executor:91 -   Exception in task 0.0 in stage 2.0 (TID 1)
org.apache.spark.SparkException: Python   worker failed to connect back.
at   org.apache.spark.api.python.PythonWorkerFactory.createSimpleWorker(PythonWorkerFactory.scala:170)
at   org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:97)
at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:117)
at   org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:108)
at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:65)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:65)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
at org.apache.spark.scheduler.Task.run(Task.scala:121)
at   org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
at   org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
at   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by:   java.net.SocketTimeoutException: Accept timed out
at java.net.DualStackPlainSocketImpl.waitForNewConnection(Native   Method)
at   java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:135)
at   java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:404)
at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
at java.net.ServerSocket.implAccept(ServerSocket.java:545)
at java.net.ServerSocket.accept(ServerSocket.java:513)
at   org.apache.spark.api.python.PythonWorkerFactory.createSimpleWorker(PythonWorkerFactory.scala:164)
... 17 more
2019-10-17 09:49:14 WARN  TaskSetManager:66 - Lost task 0.0 in stage   2.0 (TID 1, localhost, executor driver): org.apache.spark.SparkException:   Python worker failed to connect back.
at   org.apache.spark.api.python.PythonWorkerFactory.createSimpleWorker(PythonWorkerFactory.scala:170)
at   org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:97)
at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:117)
at   org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:108)
at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:65)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)

**Comment by ClonetApp** [comment]
Fix:

Spark 2.3 version works fine and 2.4 version not working.

Edit environment variable in windows:
SPARK_HOME = C:\BIGDATA\SPARK-2.3.4-BIN-hadoop2.7
